name: Lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: YarnInstall
        run: yarn

      - name: YarnLinter
        run: yarn lint:js
